name: boptestgym
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - idna=3.4
  - openssl=3.0.9
  - pip=23.1.2
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.11
  - requests=2.29.0
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - cloudpickle==2.2.1
      - cmake==3.26.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - farama-notifications==0.0.4
      - filelock==3.12.2
      - fonttools==4.40.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - jax-jumpy==1.0.0
      - jinja2==3.1.2
      - kiwisolver==1.4.4
      - lit==16.0.6
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.25.0
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - pyparsing==3.1.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - scipy==1.11.1
      - shimmy==1.1.0
      - six==1.16.0
      - stable-baselines3==2.0.0
      - sympy==1.12
      - typing-extensions==4.7.1
      - tzdata==2023.3
 